version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/http-metrics-middleware
    steps:
      - checkout
      - run:
          name: greenkeeper-lockfile - Update
          command: |
            sudo npm install -g greenkeeper-lockfile@1
            greenkeeper-lockfile-update
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install --no-save
      - run: greenkeeper-lockfile-upload
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Create report directory
          command: mkdir -p ./reports
      - run:
          name: Update version
          command: |
            VER=$(node -e "console.log(require('./package.json').version.replace(/-[0-9]+/, '-$CIRCLE_BUILD_NUM'))")
            echo "$VER" > ./version.txt
            if (echo $VER | egrep -- '-[0-9]+$' 1> /dev/null); then
              npm version $VER --no-git-tag-version
            fi
      - run: npm run lint
      - run: npm run test:codeclimate
